In [15]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import networkx as nx
import itertools

In [16]:
file_path ='/content/drive/MyDrive/MASTER/TESI/dati/pair_sl.tsv'
try:
    grafo = pd.read_csv(file_path, sep = "\t")
except Exception as e:
    print(f"An error occurred while loading the file: {e}")

In [17]:
grafo

    Uniprot ID 1 Uniprot ID 2  Occurrences
0         P00749       P04004            1
1         P00749       Q03405            1
2         P04004       Q03405            1
3         P00777       P68390           15
4         P00766       P00766           15
..           ...          ...          ...
490       P76015       P76016            4
491       P76016       P76016            1
492       P03172       P03172            1
493       P03172       Q15223            4
494       Q15223       Q15223            1

[495 rows x 3 columns]

In [23]:
G = nx.from_pandas_edgelist(grafo, "Uniprot ID 1", "Uniprot ID 2", edge_attr='Occurrences')
rows = []
for i, cc in enumerate(nx.connected_components(G)):
  for node in cc:
    rows.append({"node": node, "CC_ID": i})

cc_df = pd.DataFrame(rows)
print(cc_df.shape)
cc_df
#cc_df.to_csv("connected_components.tsv", sep="\t", index=False)

(325, 2)

       node  CC_ID
0    P04004      0
1    Q03405      0
2    P00749      0
3    P01062      1
4    P68436      1
..      ...    ...
320  Q93034    109
321  O14508    109
322  P83940    109
323  P76016    110
324  P76015    110

[325 rows x 2 columns]

In [27]:
cc_weights = {}
for i, cc_nodes in enumerate(nx.connected_components(G)):
    subgraph = G.subgraph(cc_nodes)
    total_weight = sum(data.get('Occurrences', 0) for u, v, data in subgraph.edges(data=True))
    cc_weights[i] = total_weight

weights = []
i = 0
for id in cc_df['CC_ID']:
  weights.append(cc_weights[id])

cc_df['Weight Sum']=weights

In [19]:
nodes_per_cc = cc_df['CC_ID'].value_counts().to_dict()
for i in range(1,112):
  print(i-1, nodes_per_cc[i-1])

0 3
1 23
2 4
3 16
4 35
5 4
6 5
7 2
8 2
9 3
10 1
11 1
12 6
13 3
14 2
15 2
16 3
17 1
18 2
19 2
20 3
21 3
22 4
23 2
24 3
25 3
26 1
27 2
28 1
29 3
30 2
31 1
32 2
33 2
34 3
35 2
36 2
37 1
38 2
39 2
40 1
41 2
42 2
43 3
44 1
45 1
46 1
47 3
48 3
49 2
50 2
51 1
52 2
53 2
54 2
55 3
56 4
57 2
58 2
59 2
60 2
61 2
62 2
63 4
64 4
65 3
66 3
67 2
68 2
69 3
70 2
71 2
72 2
73 2
74 3
75 4
76 2
77 2
78 2
79 2
80 2
81 2
82 2
83 3
84 2
85 2
86 2
87 4
88 2
89 2
90 3
91 1
92 1
93 2
94 1
95 2
96 2
97 3
98 2
99 2
100 2
101 2
102 3
103 4
104 2
105 2
106 2
107 3
108 2
109 4
110 2

In [21]:
grafo.columns

Index(['Uniprot ID 1', 'Uniprot ID 2', 'Occurrences'], dtype='object')

In [28]:
cc_df

       node  CC_ID  Weight Sum
0    P04004      0           3
1    Q03405      0           3
2    P00749      0           3
3    P01062      1         147
4    P68436      1         147
..      ...    ...         ...
320  Q93034    109           6
321  O14508    109           6
322  P83940    109           6
323  P76016    110           6
324  P76015    110           6

[325 rows x 3 columns]

In [29]:
cc_df.to_csv('CC_data.tsv', sep = '\t')