In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import re
import requests
import json

def get_entry_from_api(pdb_id, apiurl):
    """
    This function will make a call to the PDBe API using
    the PDB id and API url provided as arguments

    :param pdb_id: String,
    :param api_url: String
    :return: Dict or None
    """
    if not re.match("[0-9][A-Za-z][A-Za-z0-9]{2}", pdb_id):
        print("Invalid PDB id")
        return None

    # Make a GET call to the API URL
    get_request = requests.get(url=apiurl+pdb_id)

    if get_request.status_code == 200:
        # If there is data returned (with HTML status code 200)
        # then return the data in JSON format
        return get_request.json()
    else:
        # If there is no data, print status code and response
        print(get_request.status_code, get_request.text)
        return None

In [ ]:
pdb = "1cbs"
chain_of_interest = "A"
url = f"https://www.ebi.ac.uk/pdbe/api/mappings/uniprot/{pdb}"
data = requests.get(url).json()
for uniprot, info in data[pdb]["UniProt"].items():
  if chain_of_interest in info["chains"]:
    print(pdb, chain_of_interest, "→", uniprot)

In [ ]:
file_path = '/content/drive/MyDrive/dati/swpdb.tsv'
try:
    uniprot = pd.read_csv(file_path, delimiter="\t")
except Exception as e:
    print(f"An error occurred while loading the file: {e}")

In [ ]:
uniprot.shape

(658, 4)

In [ ]:
summary = "https://www.ebi.ac.uk/pdbe/api/pdb/entry/summary/"
experiment = "https://www.ebi.ac.uk/pdbe/api/pdb/entry/experiment/"
uniprot_mapping = "https://www.ebi.ac.uk/pdbe/api/mappings/uniprot/"

In [ ]:
pdbs = list(uniprot['From'].value_counts().to_dict().keys())

In [ ]:
len(pdbs)

311

In [ ]:
experimental_method = []
resolution = []
for el in pdbs:
  protein = get_entry_from_api(el, experiment)
  experimental_method.append(protein[el.lower()][0]['experimental_method'])
  resolution.append(protein[el.lower()][0].get("resolution"))

In [ ]:
unis = list(uniprot.groupby('From')['Entry'].apply(list).to_dict().values())
len(unis)

311

In [ ]:
metadata = pd.DataFrame({"PDB":pdbs, "Uniprot(s)": unis, "Method":experimental_method, "Resolution": resolution})
metadata.shape

(311, 4)

In [ ]:
method_dist = metadata[['Method']].value_counts().to_dict()
for key in method_dist:
  print(str(key)[2:-3], method_dist[key])

X-ray diffraction 309
Solution NMR 2

In [ ]:
print(min(metadata['Resolution']))

1.1

In [ ]:
print(max(metadata['Resolution']))

5.4

In [ ]:
resolution_dist = metadata[['Resolution']].value_counts().to_dict()

In [ ]:
coverage = {}
for el in pdbs:
  data = get_entry_from_api(el, uniprot_mapping)
  coverage[el]={}
  for uniprot_id, details in data[el.lower()]["UniProt"].items():
      coverage[el][uniprot_id]=-1
      for m in details["mappings"]:
        start = m["start"]["residue_number"]
        end = m["end"]["residue_number"]
        covered_residues = end - start + 1
        if coverage[el][uniprot_id]<covered_residues:
          coverage[el][uniprot_id]=covered_residues
len(coverage)

311

In [ ]:
coverage

{'1BD2': {'P04439': 275,
  'P61769': 99,
  'P0C213': 9,
  'P04437': 91,
  'P01848': 93,
  'A0A0K0K1A5': 95,
  'A0A5B9': 129},
 '1AO7': {'P04439': 275,
  'P61769': 99,
  'P14079': 9,
  'A0A075B6T6': 90,
  'P01848': 93,
  'P01850': 129},
 '2BNQ': {'P04439': 275,
  'P61769': 99,
  'P78358': 8,
  'A0A0B4J279': 92,
  'P01848': 89,
  'A0A0K0K1A5': 93,
  'P01850': 129},
 '2VLR': {'P04439': 275,
  'P61769': 99,
  'P03485': 9,
  'P01848': 89,
  'P01850': 129},
 '2BNR': {'P04439': 275,
  'P61769': 99,
  'P78358': 9,
  'A0A0B4J279': 92,
  'P01848': 89,
  'A0A0K0K1A5': 93,
  'P01850': 129},
 '1OGA': {'P04439': 275, 'P61769': 99, 'P01848': 92, 'P01850': 129},
 '2AK4': {'P01889': 276,
  'P61769': 99,
  'P03206': 13,
  'P01848': 93,
  'P01850': 129},
 '2P5E': {'P04439': 275, 'P61769': 99, 'P78358': 9, 'P01848': 79},
 '1LP9': {'P04439': 275,
  'P61769': 99,
  'Q9NPA0': 9,
  'P01849': 79,
  'P04213': 113},
 '4JFF': {'P04439': 275,
  'P61769': 99,
  'Q16655': 10,
  'P01848': 87,
  'P01850': 129},
 '2J8U': {'P04439': 275,
  'P61769': 99,
  'Q9NPA0': 9,
  'P01849': 79,
  'P04213': 113},
 '1MI5': {'P01889': 277,
  'P61769': 99,
  'Q3KST2': 9,
  'P01848': 89,
  'P01850': 129},
 '4MNQ': {'P04439': 275,
  'P61769': 99,
  'O14746': 9,
  'H2RG00': 87,
  'K7N5N2': 89,
  'P01850': 129},
 '2UWE': {'P04439': 275, 'P61769': 99, 'Q9NPA0': 9, 'P04213': 113},
 '2JCC': {'P04439': 275, 'P61769': 99, 'Q9NPA0': 9, 'P01849': 79},
 '4JFE': {'P04439': 275, 'P61769': 99, 'P01848': 87, 'P01850': 129},
 '3QIB': {'P04224': 191, 'P04230': 196, 'P01848': 93, 'P00039': 12},
 '3BN9': {'Q9Y5Y6': 241, 'P01857': 107},
 '4OZG': {'P01909': 183,
  'P01920': 192,
  'Q2YD82': 194,
  'P01850': 129,
  'P04722': 10},
 '4N8V': {'P04439': 274, 'P61769': 99, 'Q76ZQ3': 9, 'P43631': 200},
 '3VR6': {'Q08636': 593, 'Q08637': 458, 'P43435': 210, 'P43455': 103},
 '4JGH': {'O14508': 167, 'P62869': 118, 'P83940': 96, 'Q93034': 377},
 '4JFD': {'P04439': 275, 'P61769': 99, 'P01848': 86, 'P01850': 129},
 '5E9D': {'P04439': 275,
  'P61769': 99,
  'Q16655': 10,
  'A0A075B6T6': 91,
  'A0A0K0K1A5': 93},
 '3BT1': {'P00749': 133, 'P04004': 40, 'Q03405': 281},
 '1AHW': {'P01837': 107, 'P01868': 97, 'P13726': 219},
 '3QDJ': {'P04439': 275, 'P61769': 99, 'P01848': 89},
 '3QDG': {'P04439': 275, 'P61769': 99, 'P01848': 89},
 '4L3E': {'P04439': 275, 'P61769': 99, 'Q16655': 10},
 '3H9S': {'P04439': 275, 'P61769': 99, 'P38110': 9},
 '4B0M': {'P26949': 136, 'P26948': 149, 'P26926': 235},
 '3D3V': {'P04439': 275, 'P61769': 99, 'P01850': 129},
 '4PWX': {'Q12154': 353, 'Q12125': 280, 'Q12285': 54},
 '3PWP': {'P04439': 275, 'P61769': 99, 'P01848': 89},
 '4FTV': {'P04439': 275, 'P61769': 99, 'P0C213': 9},
 '3SZK': {'P69905': 141, 'P68871': 146, 'Q8NW39': 144},
 '1VFB': {'P01635': 95, 'P01820': 96, 'P00698': 129},
 '1DVF': {'P01635': 95, 'P01820': 96, 'P01646': 107, 'A0NA69': 98},
 '1JRH': {'P01869': 97, 'P15260': 108, 'P01837': 107},
 '1DQJ': {'P01837': 107, 'P01865': 96, 'P00698': 129},
 '1CBW': {'P00767': 13, 'P00766': 131, 'P00974': 58},
 '4NKQ': {'P32927': 414, 'P15509': 288, 'P04141': 127},
 '3SE3': {'P17181': 409, 'P01563': 165, 'P48551': 199},
 '4K71': {'P02768': 585, 'P55899': 274, 'P61769': 99},
 '2DSQ': {'P22692': 92, 'P05019': 70, 'P08833': 94},
 '1MLC': {'P01837': 107, 'P01868': 102, 'P00698': 129},
 '3SE4': {'P17181': 409, 'P05000': 174, 'P48551': 199},
 '3AAA': {'P13127': 286, 'P14315': 277, 'P58546': 118},
 '3Q3J': {'O75051': 111, 'Q92730': 196},
 '3NVQ': {'O75326': 590, 'O60486': 473},
 '4YH7': {'Q64487': 834, 'P59823': 334},
 '5CXB': {'G0SFB5': 495, 'G0SCK6': 369},
 '3NVN': {'Q8JL80': 385, 'O60486': 473},
 '2REX': {'O43157': 120, 'Q92730': 196},
 '4RS1': {'P04141': 112, 'P15509': 281},
 '5CYK': {'G0SFB5': 495, 'G0SCK6': 369},
 '1U7F': {'P84022': 198, 'Q13485': 239},
 '5E6P': {'B2RXS4': 617, 'O15085': 84},
 '2GYK': {'P13479': 86, 'P09883': 133},
 '1KIQ': {'P01635': 95, 'P00698': 129},
 '1KIP': {'P01635': 95, 'P00698': 129},
 '1KIR': {'P01820': 96, 'P00698': 129},
 '1REW': {'P12643': 114, 'P36894': 129},
 '1EMV': {'P13479': 86, 'P09883': 133},
 '1JTG': {'P62593': 263, 'P35804': 165},
 '1FR2': {'P13479': 86, 'P09883': 133},
 '1N8O': {'P00766': 131, 'P23827': 142},
 '1NCA': {'P01865': 100, 'P03472': 389},
 '1S1Q': {'Q99816': 145, 'P0CG48': 76},
 '1XD3': {'P15374': 230, 'P0CG48': 75},
 '4CPA': {'P00730': 307, 'P01075': 38},
 '1KTZ': {'P10600': 112, 'P37173': 122},
 '1LFD': {'Q03386': 87, 'P01112': 167},
 '1S0W': {'P62593': 263, 'P35804': 165},
 '2BTF': {'P60712': 374, 'P02584': 139},
 '2AJF': {'Q9BYF1': 597, 'P59594': 180},
 '2A9K': {'P11233': 175, 'P15879': 211},
 '2C0L': {'P50542': 305, 'P22307': 122},
 '3N4I': {'P0AD64': 265, 'P35804': 165},
 '2FTL': {'P00760': 223, 'P00974': 58},
 '2G2U': {'P0AD64': 265, 'P35804': 165},
 '2G2W': {'P0AD64': 265, 'P35804': 165},
 '1EAW': {'Q9Y5Y6': 241, 'P00974': 58},
 '1FC2': {'P38507': 58, 'P01857': 223},
 '4YEB': {'Q80TS3': 297, 'Q8BGT1': 358},
 '4YFD': {'Q64487': 491, 'Q61730': 331},
 '4G0N': {'P01112': 166, 'P04049': 78},
 '1SBN': {'P00782': 275, 'P01051': 70},
 '1ACB': {'P00766': 245, 'P01051': 70},
 '1GUA': {'P62834': 167, 'P04049': 81},
 '1GCQ': {'P62993': 59, 'P27870': 66},
 '1E96': {'P63000': 191, 'P19878': 203},
 '1SBB': {'P01852': 126, 'P01552': 239},
 '1X1X': {'P00648': 110, 'P11540': 89},
 '1B2S': {'P00648': 110, 'P11540': 90},
 '1B2U': {'P00648': 110, 'P11540': 90},
 '1X1W': {'P00648': 110, 'P11540': 90},
 '1B3S': {'P00648': 110, 'P11540': 90},
 '2VLN': {'P13479': 86, 'P09883': 133},
 '2VLP': {'P13479': 86, 'P09883': 133},
 '2WPT': {'P04482': 86, 'P09883': 133},
 '2HRK': {'P46655': 191, 'P46672': 122},
 '3BP8': {'P50456': 406, 'P69786': 75},
 '3D5R': {'P01024': 292, 'A6QG59': 65},
 '2VLO': {'P13479': 86, 'P09883': 133},
 '2VLQ': {'P13479': 86, 'P09883': 133},
 '2GOX': {'P01024': 292, 'P68799': 65},
 '3D5S': {'P01024': 292, 'A6QG59': 65},
 '1EFN': {'P06241': 59, 'P03406': 152},
 '1UUZ': {'Q9HXB1': 129, 'P00698': 129},
 '2J0T': {'P03956': 169, 'P01033': 126},
 '2OOB': {'Q13191': 50, 'P0CH28': 76},
 '2PCB': {'P00431': 294, 'P00004': 104},
 '2PCC': {'P00431': 294, 'P00044': 108},
 '2B12': {'P00431': 294, 'P00044': 108},
 '2B11': {'P00431': 294, 'P00044': 108},
 '2B10': {'P00431': 294, 'P00044': 108},
 '2B0Z': {'P00431': 294, 'P00044': 108},
 '2HLE': {'P54760': 180, 'P52799': 138},
 '1AK4': {'P62937': 165, 'P12497': 145},
 '1SIB': {'P00782': 275, 'P01051': 70},
 '1CSE': {'P00780': 274, 'P01051': 70},
 '2NU2': {'P00777': 185, 'P68390': 51},
 '1CHO': {'P00766': 131, 'P68390': 56},
 '1PPF': {'P08246': 218, 'P68390': 56},
 '1R0R': {'P00780': 274, 'P68390': 51},
 '3SGB': {'P00777': 185, 'P68390': 56},
 '1SMF': {'P00760': 223, 'P01062': 22},
 '1FY8': {'P00763': 231, 'P00974': 58},
 '3TGK': {'P00763': 230, 'P00974': 65},
 '1F5R': {'P00763': 230, 'P00974': 65},
 '3BTD': {'P00760': 223, 'P00974': 58},
 '3BTE': {'P00760': 223, 'P00974': 58},
 '3BTF': {'P00760': 223, 'P00974': 58},
 '3BTG': {'P00760': 223, 'P00974': 58},
 '3BTH': {'P00760': 223, 'P00974': 58},
 '3BTM': {'P00760': 223, 'P00974': 58},
 '3BTQ': {'P00760': 223, 'P00974': 58},
 '3BTW': {'P00760': 223, 'P00974': 58},
 '1A4Y': {'P13489': 460, 'P03950': 123},
 '1Z7X': {'P13489': 461, 'P07998': 128},
 '1A22': {'P01241': 191, 'P10912': 238},
 '1BP3': {'P01241': 191, 'P16471': 211},
 '3MZG': {'P01236': 185, 'P16471': 210},
 '3N06': {'P01236': 185, 'P16471': 210},
 '3N0P': {'P01236': 185, 'P16471': 210},
 '3NCB': {'P01236': 185, 'P16471': 210},
 '3NCC': {'P01236': 185, 'P16471': 210},
 '1F47': {'P0A9A6': 17, 'P77173': 144},
 '1FCC': {'P01857': 206, 'P19909': 56},
 '1GC1': {'P01730': 185, 'P04578': 163},
 '1DAN': {'P08709': 254, 'P13726': 121},
 '3HFM': {'P01837': 107, 'P00698': 129},
 '1HE8': {'P48736': 959, 'P01112': 166},
 '1MAH': {'P21836': 543, 'P0C1Z0': 61},
 '1H9D': {'Q01196': 134, 'Q13951': 134},
 '1GRN': {'P60953': 191, 'Q07960': 203},
 '1GL1': {'P00766': 245, 'P80060': 36},
 '1GL0': {'P00766': 245, 'P80060': 35},
 '1FFW': {'P0AE67': 128, 'P07363': 134},
 '1P6A': {'P36711': 185, 'P78310': 123},
 '1KAC': {'P36711': 185, 'P78310': 124},
 '2J1K': {'P78310': 128, 'Q65914': 186},
 '2NU4': {'P00777': 185, 'P68390': 51},
 '1P69': {'P36711': 185, 'P78310': 123},
 '1CT4': {'P00777': 185, 'P68390': 51},
 '1CT0': {'P00777': 185, 'P68390': 51},
 '1CSO': {'P00777': 185, 'P68390': 51},
 '2SGP': {'P00777': 185, 'P68390': 51},
 '3BTT': {'P00760': 223, 'P00974': 58},
 '1SGQ': {'P00777': 185, 'P68390': 51},
 '1SGE': {'P00777': 185, 'P68390': 51},
 '1SGN': {'P00777': 185, 'P68390': 51},
 '3QFJ': {'P04439': 275, 'P61769': 99},
 '1FSS': {'P04058': 537, 'P0C1Z0': 61},
 '5F4E': {'Q8IYV9': 233, 'A6ND01': 209},
 '4G2V': {'Q8VDU0': 336, 'Q5SYB0': 38},
 '3SF4': {'P81274': 402, 'Q1MX18': 47},
 '4WND': {'P81274': 402, 'Q14CM0': 48},
 '2SGQ': {'P00777': 185, 'P68390': 51},
 '1CT2': {'P00777': 185, 'P68390': 51},
 '1SGD': {'P00777': 185, 'P68390': 51},
 '1SGP': {'P00777': 185, 'P68390': 51},
 '2NU1': {'P00777': 185, 'P68436': 51},
 '1SGY': {'P00777': 185, 'P68390': 51},
 '2NU0': {'P00777': 185, 'P68436': 51},
 '4P5T': {'P14434': 182, 'P14483': 195},
 '4P23': {'P14434': 179, 'P14483': 189},
 '3C60': {'P14434': 182, 'P14483': 189},
 '2C5D': {'Q14393': 418, 'P30530': 195},
 '4X4M': {'P01857': 217, 'P12314': 269},
 '4RA0': {'Q14393': 401, 'P30530': 195},
 '4Y61': {'Q64487': 391, 'Q810C0': 266},
 '1QSE': {'P04439': 274, 'P61769': 100},
 '3BX1': {'P29600': 269, 'P07596': 181},
 '2OI9': {'P01897': 179, 'P01738': 110, 'A2NTY6': 110},
 '1B41': {'P22303': 539, 'P0C1Z0': 61},
 '3UIG': {'O15392': 142, 'P68431': 15},
 '4MYW': {'P03172': 285, 'Q15223': 306},
 '3U82': {'Q69091': 285, 'Q15223': 306},
 '4NZW': {'Q9Y376': 327, 'O00506': 293},
 '4NM8': {'Q91MA7': 319, 'S6C4S0': 224, 'P01834': 107},
 '1XGP': {'P01837': 107, 'P00698': 129},
 '1XGQ': {'P01837': 107, 'P00698': 129},
 '1XGU': {'P01837': 107, 'P00698': 129},
 '3Q8D': {'P0A7H3': 242, 'P0AGE0': 9},
 '2AW2': {'Q7Z6A9': 112, 'Q92956': 104},
 '3KBH': {'Q9BYF1': 597, 'Q6Q1S2': 136},
 '3R9A': {'P21549': 392, 'P50542': 325},
 '4FZA': {'Q9Y376': 324, 'Q9P289': 280},
 '3B4V': {'P08476': 116, 'O95633': 237},
 '2B0U': {'P08476': 116, 'P19883': 288},
 '3HH2': {'O08689': 109, 'P19883': 288},
 '3UII': {'O15392': 142, 'P68431': 10},
 '3LB6': {'P35225': 132, 'Q14627': 380},
 '3RF3': {'P18206': 258, 'P18010': 25},
 '4O27': {'Q9Y376': 323, 'Q9Y6E0': 280},
 '4OFY': {'B1Q236': 253, 'Q9U3P2': 411},
 '2DVW': {'Q9Z2X2': 231, 'P43686': 82},
 '3F1S': {'Q9UK55': 385, 'P22891': 276},
 '3M63': {'P54860': 961, 'P48510': 75},
 '3M62': {'P54860': 961, 'P32628': 84},
 '3SEK': {'O08689': 109, 'O95633': 209},
 '1C4Z': {'Q05086': 358, 'P68036': 154},
 '3MZW': {'P04626': 624, 'P38507': 58},
 '3S9D': {'P01563': 165, 'P48551': 196},
 '2B2X': {'P18614': 214, 'P01868': 102},
 '4LRX': {'P76015': 356, 'P76016': 318},
 '4JEU': {'P61765': 590, 'P32851': 242},
 '4J2L': {'P54253': 127, 'Q96RK0': 26},
 '4HSA': {'Q16552': 122, 'Q96F46': 286},
 '4GNK': {'P21279': 353, 'Q01970': 1225},
 '4EKD': {'P21279': 342, 'P41220': 132},
 '1E50': {'Q01196': 134, 'Q13951': 134},
 '4BFI': {'Q9ES57': 203, 'O54901': 202},
 '1WQJ': {'P22692': 80, 'P05019': 70},
 '4E6K': {'Q9HY79': 158, 'Q9HY80': 73},
 '1KNE': {'P05205': 60, 'P02299': 16},
 '2KSO': {'P29317': 65, 'O15357': 59},
 '1KBH': {'Q9Y6Q9': 47, 'P45481': 59},
 '4L0P': {'P29320': 173, 'P52803': 140},
 '5TAR': {'P01116': 184, 'O43924': 148},
 '3EG5': {'P60766': 178, 'O08808': 383},
 '1YCS': {'P04637': 199, 'Q13625': 203},
 '1C1Y': {'P62834': 167, 'P04049': 77},
 '3KUD': {'P01112': 166, 'P04049': 81},
 '1K8R': {'P01112': 166, 'P28829': 110},
 '1BRS': {'P00648': 110, 'P11540': 89},
 '1IAR': {'P05112': 129, 'P24394': 207},
 '2SIC': {'P00782': 275, 'P01006': 107},
 '1Y1K': {'P00782': 275, 'Q40059': 64},
 '1Y33': {'P00782': 275, 'Q40059': 64},
 '1Y34': {'P00782': 275, 'Q40059': 64},
 '1Y3B': {'P00782': 275, 'Q40059': 64},
 '1Y3C': {'P00782': 275, 'Q40059': 64},
 '1Y48': {'P00782': 275, 'Q40059': 64},
 '1Y3D': {'P00782': 275, 'Q40059': 64},
 '1TM4': {'P00782': 275, 'Q40059': 64},
 '1TM5': {'P00782': 275, 'Q40059': 64},
 '1TM3': {'P00782': 275, 'Q40059': 64},
 '1TM7': {'P00782': 275, 'Q40059': 64},
 '1TMG': {'P00782': 275, 'Q40059': 64},
 '1TO1': {'P00782': 275, 'Q40059': 64},
 '3EQS': {'Q00987': 85},
 '3LNZ': {'Q00987': 85},
 '3EQY': {'O15151': 85},
 '5K39': {'Q06853': 160, 'A3DGE8': 164},
 '5XCO': {'P01116': 169},
 '5UFE': {'P01116': 166},
 '5UFQ': {'P01116': 166},
 '3W2D': {'P01552': 239},
 '4KRL': {'P00533': 204},
 '4KRO': {'P00533': 618},
 '4KRP': {'P00533': 613},
 '2NYY': {'P0DPI1': 1295},
 '2NZ9': {'P0DPI1': 1295},
 '2BDN': {'P13500': 76},
 '1JTD': {'P62593': 263, 'O87916': 273},
 '3WWN': {'O50147': 269, 'Q9ZND7': 54},
 '4I77': {'P35225': 112},
 '3L5X': {'P35225': 112},
 '4JPK': {'P04578': 116},
 '1BJ1': {'P15692': 102},
 '1CZ8': {'P15692': 94},
 '1MHP': {'P18614': 192},
 '3G6D': {'P35225': 112},
 '1XGR': {'P00698': 129},
 '1XGT': {'P00698': 129},
 '3N85': {'P04626': 624},
 '4U6H': {'P07612': 184},
 '1YY9': {'P00533': 618},
 '4GXU': {'Q9WFX3': 327},
 '3LZF': {'Q9WFX3': 327},
 '4HRN': {'P04626': 97},
 '1N8Z': {'P04626': 607},
 '2E7L': {'A2NTU7': 112, 'A2NTY6': 110, 'P01897': 181},
 '2J12': {'Q80S15': 194, 'P78310': 128},
 '1NMB': {'P05803': 470},
 '3NPS': {'Q9Y5Y6': 241},
 '3BK3': {'P12643': 114, 'Q5D734': 66},
 '2JEL': {'P0AA04': 85},
 '2O3B': {'P38446': 240, 'A0ACD6B9A1': 134},
 '2VIS': {'Q99LC4': 111, 'P03437': 282},
 '2VIR': {'Q99LC4': 111, 'P03437': 282},
 '1JCK': {'P0A0L5': 239},
 '1M9E': {'P62937': 164, 'Q72497': 146},
 '2B42': {'Q8H0K8': 381, 'P18429': 185},
 '2I26': {'P00698': 129, 'Q8JGG7': 84},
 '5C6T': {'P13201': 612},
 '1YQV': {'P00698': 129},
 '1TM1': {'P00782': 275, 'Q40059': 64}}

In [ ]:
pdbs = []
uniprots = []
coverages = []
expmet = []
res = []
i = 0
for key in coverage:
  for k in coverage[key]:
    pdbs.append(key)
    uniprots.append(k)
    coverages.append(coverage[key][k])
    expmet.append(experimental_method[i])
    res.append(resolution[i])
  i+=1
coverage_df = pd.DataFrame({'PDB':pdbs, 'Experimental Method':expmet, 'Resolution':res, 'Uniprot':uniprots, 'Coverage': coverages})

In [ ]:
coverage_df.shape

(682, 5)

In [ ]:
coverage_df

      PDB Experimental Method  Resolution Uniprot  Coverage
0    1BD2   X-ray diffraction         2.5  P04439       275
1    1BD2   X-ray diffraction         2.5  P61769        99
2    1BD2   X-ray diffraction         2.5  P0C213         9
3    1BD2   X-ray diffraction         2.5  P04437        91
4    1BD2   X-ray diffraction         2.5  P01848        93
..    ...                 ...         ...     ...       ...
677  2I26   X-ray diffraction         2.5  Q8JGG7        84
678  5C6T   X-ray diffraction         3.6  P13201       612
679  1YQV   X-ray diffraction         1.7  P00698       129
680  1TM1   X-ray diffraction         1.7  P00782       275
681  1TM1   X-ray diffraction         1.7  Q40059        64

[682 rows x 5 columns]

In [ ]:
up = uniprot['Entry'].to_list()
lengths = uniprot['Length'].to_list()

In [ ]:
leng={}
for i in range(len(up)):
  leng[up[i]]=lengths[i]

In [ ]:
coverage_df['Length'] = coverage_df['Uniprot'].map(leng)
display(coverage_df.head())

    PDB Experimental Method  Resolution Uniprot  Coverage  Length
0  1BD2   X-ray diffraction         2.5  P04439       275   365.0
1  1BD2   X-ray diffraction         2.5  P61769        99   119.0
2  1BD2   X-ray diffraction         2.5  P0C213         9   353.0
3  1BD2   X-ray diffraction         2.5  P04437        91   119.0
4  1BD2   X-ray diffraction         2.5  P01848        93   140.0

In [ ]:
length = coverage_df['Length'].to_numpy()
coverage = coverage_df['Coverage'].to_numpy()
covperc = coverage/length*100
coverage_df['Coverage (%)']=pd.Series(covperc)
coverage_df.head()

,PDB,Experimental Method,Resolution,Uniprot,Coverage,Length,Coverage (%)
0,1BD2,X-ray diffraction,2.5,P04439,275,365.0,75.342466
1,1BD2,X-ray diffraction,2.5,P61769,99,119.0,83.193277
2,1BD2,X-ray diffraction,2.5,P0C213,9,353.0,2.549575
3,1BD2,X-ray diffraction,2.5,P04437,91,119.0,76.470588
4,1BD2,X-ray diffraction,2.5,P01848,93,140.0,66.428571

In [ ]:
coverage_df = coverage_df.rename(columns={'Uniprot Length': 'Length'})
display(coverage_df.head())

,PDB,Experimental Method,Resolution,Uniprot,Coverage,Length,Coverage (%)
0,1BD2,X-ray diffraction,2.5,P04439,275,365.0,75.342466
1,1BD2,X-ray diffraction,2.5,P61769,99,119.0,83.193277
2,1BD2,X-ray diffraction,2.5,P0C213,9,353.0,2.549575
3,1BD2,X-ray diffraction,2.5,P04437,91,119.0,76.470588
4,1BD2,X-ray diffraction,2.5,P01848,93,140.0,66.428571

In [ ]:
file_path = '/content/drive/MyDrive/dati/unr.tsv'
try:
    unrev = pd.read_csv(file_path, delimiter="\t")
except Exception as e:
    print(f"An error occurred while loading the file: {e}")

In [ ]:
pdbs = list(unrev['From'].value_counts().to_dict().keys())

In [ ]:
len(pdbs)

8

In [ ]:
experimental_method = []
resolution = []
for el in pdbs:
  protein = get_entry_from_api(el, experiment)
  experimental_method.append(protein[el.lower()][0]['experimental_method'])
  resolution.append(protein[el.lower()][0].get("resolution"))

In [ ]:
unis = list(unrev.groupby('From')['Entry'].apply(list).to_dict().values())
len(unis)

8

In [ ]:
metadata = pd.DataFrame({"PDB":pdbs, "Uniprot(s)": unis, "Method":experimental_method, "Resolution": resolution})
metadata.shape

(8, 4)

In [ ]:
method_dist = metadata[['Method']].value_counts().to_dict()
for key in method_dist:
  print(str(key)[2:-3], method_dist[key])

X-ray diffraction 8

In [ ]:
print(min(metadata['Resolution']))

1.26

In [ ]:
print(max(metadata['Resolution']))

3.166

In [ ]:
resolution_dist = metadata[['Resolution']].value_counts().to_dict()

In [ ]:
coverage = {}
for el in pdbs:
  data = get_entry_from_api(el, uniprot_mapping)
  coverage[el]={}
  for uniprot_id, details in data[el.lower()]["UniProt"].items():
      coverage[el][uniprot_id]=-1
      for m in details["mappings"]:
        start = m["start"]["residue_number"]
        end = m["end"]["residue_number"]
        covered_residues = end - start + 1
        if coverage[el][uniprot_id]<covered_residues:
          coverage[el][uniprot_id]=covered_residues
len(coverage)

8

In [ ]:
coverage

{'4CVW': {'O48541': 482, 'Q2V8X0': 114},
 '4HFK': {'A0A0H3CIJ2': 163, 'A0A0H3CIX8': 99},
 '3QHY': {'Q93T42': 271, 'O87916': 271},
 '3NGB': {'Q0ED31': 162},
 '3SE9': {'Q0ED31': 353},
 '4ZS6': {'W6A0A7': 223},
 '3SE8': {'Q0ED31': 353},
 '5M2O': {'A0AEF4': 146}}

In [ ]:
pdbs = []
uniprots = []
coverages = []
expmet = []
res = []
i = 0
for key in coverage:
  for k in coverage[key]:
    pdbs.append(key)
    uniprots.append(k)
    coverages.append(coverage[key][k])
    expmet.append(experimental_method[i])
    res.append(resolution[i])
  i+=1
df = pd.DataFrame({'PDB':pdbs, 'Experimental Method':expmet, 'Resolution':res, 'Uniprot':uniprots, 'Coverage': coverages})

In [ ]:
up = unrev['Entry'].to_list()
lengths = unrev['Length'].to_list()

In [ ]:
leng={}
for i in range(len(up)):
  leng[up[i]]=lengths[i]

In [ ]:
df['Length'] = df['Uniprot'].map(leng)
display(df.head())

    PDB Experimental Method  Resolution     Uniprot  Coverage  Length
0  4CVW   X-ray diffraction        2.67      O48541       482     904
1  4CVW   X-ray diffraction        2.67      Q2V8X0       114     147
2  4HFK   X-ray diffraction        2.10  A0A0H3CIJ2       163     163
3  4HFK   X-ray diffraction        2.10  A0A0H3CIX8        99     117
4  3QHY   X-ray diffraction        2.06      Q93T42       271     309

In [ ]:
length = df['Length'].to_numpy()
coverage = df['Coverage'].to_numpy()
covperc = coverage/length*100
df['Coverage (%)']=pd.Series(covperc)
df.head()

,PDB,Experimental Method,Resolution,Uniprot,Coverage,Length,Coverage (%)
0,4CVW,X-ray diffraction,2.67,O48541,482,904,53.318584
1,4CVW,X-ray diffraction,2.67,Q2V8X0,114,147,77.551020
2,4HFK,X-ray diffraction,2.10,A0A0H3CIJ2,163,163,100.000000
3,4HFK,X-ray diffraction,2.10,A0A0H3CIX8,99,117,84.615385
4,3QHY,X-ray diffraction,2.06,Q93T42,271,309,87.702265

In [ ]:
metadata = pd.concat([coverage_df, df], ignore_index=True)
display(metadata.head())

,PDB,Experimental Method,Resolution,Uniprot,Coverage,Length,Coverage (%)
0,1BD2,X-ray diffraction,2.5,P04439,275,365.0,75.342466
1,1BD2,X-ray diffraction,2.5,P61769,99,119.0,83.193277
2,1BD2,X-ray diffraction,2.5,P0C213,9,353.0,2.549575
3,1BD2,X-ray diffraction,2.5,P04437,91,119.0,76.470588
4,1BD2,X-ray diffraction,2.5,P01848,93,140.0,66.428571

In [ ]:
metadata.shape

(693, 7)

In [ ]:
metadata.to_csv('metadata.tsv', sep='\t', index=False)